[package]
name = "gameboy"
version = "0.1.0"
authors = ["Rim <rim.buei@gmail.com>"]
edition = "2018"

[dependencies]
stdweb = "*"

[[bin]]
name = "cli"
path = "src/cli.rs"

[[bin]]
name = "wasm"
path = "src/wasm.rs"
