[package]
name = "gameboy"
version = "0.3.0"
authors = ["rim-buei <rim.buei@gmail.com>"]
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[[bin]]
name = "cli"
path = "src/cli.rs"

[dependencies]
wasm-bindgen = "0.2.127"
js-sys = "0.3.104"
console_error_panic_hook = "0.1.7"

[dependencies.web-sys]
version = "0.3.104"
features = [
  "console",
  "Document",
  "Element",
  "EventTarget",
  "Event",
  "Window",
  "HtmlCanvasElement",
  "HtmlInputElement",
  "CanvasRenderingContext2d",
  "ImageData",
  "KeyboardEvent",
  "File",
  "FileList",
  "FileReader",
  "ProgressEvent",
]
