name: cargo fmt
description: Run cargo fmt
runs:
  using: composite
  steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
    - uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable
      with:
        toolchain: nightly
        components: rustfmt
    - name: Run fmt check
      run: cargo fmt --all -- --check
      shell: bash
